### ISSUE TITLE
[BUG]: Bug report template does not have all system/version information that is required

### ISSUE THREAD

**Issue by gallacher** [dell/karavi-metrics-powerflex#66]
**Describe the bug**
The bug report template should be updated to specify the following required system information:
- Kubernetes Version: [e.g. 1.18]
- karavi-metrics-powerflex Version: [e.g. 0.1.0-pre-release]
- Prometheus Version: [e.g. 2.22.0]
- Grafana Version: [e.g. 7.3.2]
- Grafana Dashboard Title: [e.g. Storage Pool and Storage Class Capacity]
- Grafana Datatable Panel plugin configuration (can be provided as a screenshot)
- Grafana Prometheus Datasource configuration (can be provided as a screenshot)
- Grafana Pie Chart Panel plugin configuration (can be provided as a screenshot)

**To Reproduce**
N/A

**Expected behavior**
The new system information should appear in the Bug report template

**Screenshots**
N/A

**Logs**
N/A

**System Information (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by ioeicicdsvc** [comment]
link: 1674
