### ISSUE TITLE
[BUG]: The latest version badge is not displaying correctly

### ISSUE THREAD

**Issue by gallacher** [dell/karavi-metrics-powerflex#67]
**Describe the bug**
The latest version badge on the root README.md file is not being rendered correctly.  It shows an error indicating "no releases or repo not found".

**To Reproduce**
Navigate to github.com/dell/karavi-metrics-powerflex

**Expected behavior**
The badge should display the latest release version of the service

**Screenshots**
![image](https://user-images.githubusercontent.com/35462391/100281047-8ffb7a80-2f3f-11eb-89f1-cc99ba74e49e.png)

**Logs**
N/A

**System Information (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by ioeicicdsvc** [comment]
link: 1673
