### ISSUE TITLE
[BUG]: Documentation does not describe the coupling/requirement with the CSI PowerFlex driver

### ISSUE THREAD

**Issue by gallacher** [dell/karavi-metrics-powerflex#69]
**Describe the bug**
The main README file does not indicate the relationship/coupling between the CSI PowerFlex driver and the Metrics for PowerFlex service.  Also, the getting started guide does not indicate that the CSI PowerFlex driver is required.

**To Reproduce**
N/A

**Expected behavior**
The main README file contains a description of how the Metrics for PowerFlex service ties in with the CSI PowerFlex driver.  Also, the getting started guide describes that the CSI PowerFlex driver is required and the specific version(s) that are required.

**Screenshots**
N/A

**Logs**
N/A

**System Information (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by ioeicicdsvc** [comment]
link: 1688
