### ISSUE TITLE
[FEATURE]: Karavi Observability Support for OpenShift

### ISSUE THREAD

**Issue by ioeicicdsvc** [dell/karavi-metrics-powerflex#79]
**Describe the feature**
This feature involves Karavi Observability supporting OpenShift versions 4.5, 4.6. 

Karavi Observability has been properly tested to qualify support for OpenShift 4.5, 4.6.

As such, the documentation is updated to reflect the supported versions of OpenShift.

**Comment by ameer-jabbar** [comment]
Will be available in karavi-observability-0.2.0

https://github.com/dell/helm-charts/pull/60 (branch: karavi-observability-0.2.0])
https://github.com/dell/karavi-topology/pull/85 (branch: main)
https://github.com/dell/karavi-metrics-powerflex/pull/81 (branch: main)
https://github.com/dell/karavi/pull/23 (branch: main)
